### ISSUE TITLE
Failures in Recommended Package Checks Do Not Fail CI Run

### ISSUE THREAD

**Issue by brodieG** [r-devel/r-svn#22]
Just noticed a failure in Matrix after making some local changes and went to check if it was me or if it had happened previously.  I was crestfallen when I saw the CI was all green for the most recent commits, but then on closer inspection I saw that the package tests had [actually failed][1].

Certainly it is the case that `make check-all` doesn't complain either, and I almost missed that the package had failed in my own runs as it takes a fair bit of careful scrolling to see the errors, but it seems like this is worth highlighting if possible.  I know very little about `make` and less about how it interacts with GA, so I can't be much help in providing a solution here.

[1]: https://github.com/r-devel/r-svn/runs/1627100474?check_suite_focus=true#step:8:1348

**Comment by jeroen** [comment]
If anything, this is a bug in base R. Our CI simply runs `make check-all` and if that succeeds then we have to assume all is OK. I agree that it would be better if `make check-all` returns an error if a package fails a check, but that is something that would need to be fixed in the R make configuration files.
